import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* Fixify Light-First Semantic Palette */
        porcelain: '#F7F4EC',
        paper: '#FFFEFA',
        'paper-2': '#F1EEE5',
        sand: '#E7E1D5',
        ink: '#18211F',
        'ink-2': '#34413D',
        'ink-3': '#5A6661',
        'ink-4': '#7C8681',
        teal: '#176B5B',
        'teal-deep': '#0D5144',
        'teal-soft': '#E2EEE9',
        'teal-wash': '#EFF6F2',
        blue: '#416B84',
        'blue-soft': '#E6EEF2',
        ochre: '#9B6A1E',
        'ochre-soft': '#F5EBD7',
        clay: '#A9523D',
        'clay-soft': '#F3E1DA',
        success: '#2F7D5B',
        'success-soft': '#E3F0E8',
        warning: '#9B6A1E',
        'warning-soft': '#F5EBD7',
        danger: '#B94A43',
        'danger-soft': '#F6E3E1',
        info: '#416B84',
        'info-soft': '#E6EEF2',
        line: '#D9DED8',
        'line-strong': '#C7CEC8',
      },
      fontFamily: {
        sans: [
          'ui-sans-serif',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Inter',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'monospace',
        ],
        serif: ['Georgia', 'Times New Roman', 'serif'],
        display: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1.2' }],
        sm: ['0.875rem', { lineHeight: '1.5' }],
        base: ['1rem', { lineHeight: '1.5' }],
        lg: ['1.125rem', { lineHeight: '1.5' }],
        xl: ['1.25rem', { lineHeight: '1.5' }],
        '2xl': ['1.5625rem', { lineHeight: '1.2' }],
        '3xl': ['1.953rem', { lineHeight: '1.2' }],
        '4xl': ['2.441rem', { lineHeight: '1.2' }],
        '5xl': ['3.052rem', { lineHeight: '1.2' }],
        '6xl': ['3.815rem', { lineHeight: '1.2' }],
      },
      spacing: {
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
      },
      borderRadius: {
        none: '0',
        xs: '0.125rem',
        sm: '0.25rem',
        base: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        sm: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
        base: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
        md: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
        lg: '0 20px 25px -5px rgb(0 0 0 / 0.1)',
        xl: '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        'shadow': '0 18px 50px rgba(24, 33, 31, 0.1)',
        'shadow-soft': '0 8px 26px rgba(24, 33, 31, 0.07)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
      },
      keyframes: {
        'fade-in-up': {
          from: {
            opacity: '0',
            transform: 'translateY(12px)',
          },
          to: {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.3s ease-out',
      },
    },
  },
  plugins: [],
};
export default config;
